AppBundle\Model\FormModel:
    properties:
        field:
            - Valid: ~

AppBundle\Model\NestedFormModel:
    properties:
        nestedField:
            - NotBlank:
                message: VALIDATION.NOT_BLANK
                groups: [groupA]
